const listaCarrosArray = [
  {
    id: 1,
    modelo: "E-type",
    marca: "Jaguar",
    ano: 1978,
    preco: "1.500.000€",
    combustivel: "gasolina",
    km: "10km",
    img: "assets/img/cars/jaguar.jpg",
    img2: "assets/img/cars/jaguar2.jpg",
    img3: "assets/img/cars/jaguar-etype.png",
    img4: "assets/img/cars/jaguar3.webp",
    lugares: "5 pessoas",
    stand: "Stand Famalicao",
    local: "Nova Iorque, EUA",
    standImg: "assets/img/cars/car-list-icon-01.png",
    estado: "disponivel",
    link: "jaguare-type.html",
  },
  {
    id: 2,
    modelo: "Dawn Drophead 1949",
    marca: "Rolls Royce",
    ano: 1949,
    preco: "7.800.000€",
    combustivel: "gasolina",
    km: "10km",
    img: "assets/img/cars/rolls-royce.jpg",
    img2: "assets/img/cars/rolls-royce2.webp",
    img3: "assets/img/cars/rolls-royce-3.avif",
    img4: "assets/img/cars/rolls-royce-4.jpg",
    lugares: "5 pessoas",
    stand: "Auto Mobilitcs",
    local: "Nova Iorque, EUA",
    standImg: "assets/img/cars/car-list-icon-02.png",
    estado: "disponivel",
    link: "rolls-royce.html",
  },
  {
    id: 3,
    modelo: "365 Speedster 1954",
    marca: "Porsche",
    ano: 1954,
    preco: "4.350.000€",
    combustivel: "gasolina",
    km: "10km",
    img: "assets/img/cars/porsche-spyder.jpg",
    img2: "assets/img/cars/porsche2.png",
    img3: "assets/img/cars/porsche3.jpg",
    img4: "assets/img/cars/porsche4.jpg",
    lugares: "5 pessoas",
    stand: "Auto Mobilitcs",
    local: "Nova Iorque, EUA",
    standImg: "assets/img/cars/car-list-icon-02.png",
    estado: "indisponivel",
    link: "porsche.html",
  },
  {
    id: 4,
    modelo: "300 SL Gullwing 1957",
    marca: "Mercedes",
    ano: 1957,
    preco: "16.350.000€",
    combustivel: "gasolina",
    km: "10km",
    img: "assets/img/cars/mercedes.jpg",
    img2: "assets/img/cars/mercedes2.webp",
    img3: "assets/img/cars/mercedes3.jpg",
    img4: "assets/img/cars/mercedes4.webp",
    lugares: "5 pessoas",
    stand: "Auto Docs",
    local: "Nova Iorque, EUA",
    standImg: "assets/img/cars/car-list-icon-03.png",
    estado: "disponivel",
    link: "mercedes.html",
  },
];
localStorage.setItem("listaCarros", JSON.stringify(listaCarrosArray));
